/*
 * English translation. Mirrors ru.js key-for-key.
 *
 * Do NOT edit this file to get yet another language. Instead, copy it
 * (or ru.js) to locale/<code>.js, keep every key path identical, and
 * only change the string values. Register the new file in dicts inside
 * index.js and point LOCALE=<code> at it. Missing keys in any locale
 * fall back to ru.js automatically (see index.js), so a partial
 * translation still works — but it's easiest to keep new locale files
 * complete from the start.
 */
module.exports = {
    common: {
        error: 'Error',
        invalidNumber: 'Invalid number',
        invalidFormat: 'Invalid format',
        notEnoughArgs: 'Not enough arguments: {usage}',
        wrongArgsCount: 'Wrong number of arguments: {usage}',
        playerNotFound: 'No player with that ID on the server',
        playerNotOnServer: 'Player is not on the server',
        accountNotFound: 'Account not found',
        accountNotFoundOwn: 'Your account was not found',
        unknown: 'unknown',
        none: '—',
        discordTokenMissing: '[Discord] DISCORD_BOT_TOKEN is not set, Discord integration disabled.'
    },

    time: {
        units: {
            s: 'sec',
            min: 'min',
            h: 'h',
            d: 'd',
            w: 'w',
            mon: 'mo'
        }
    },

    role: {
        names: {
            master: 'Owner',
            admin: 'Administrator',
            preadmin: 'Jr. Administrator',
            vip: 'VIP',
            player: 'player'
        },
        labels: {
            master: 'MASTER',
            admin: 'ADMIN',
            preadmin: 'PREADMIN',
            vip: 'VIP',
            player: 'PLAYER'
        },
        expired: 'Your role has expired =(',
        updated: '{displayName} is now {roleName}{timeStr}!',
        updatedTimed: ' for {timeStr}',
        noSuchRole: 'Invalid role: {roles}',
        cannotSetSelf: 'You cannot change your own role!',
        cannotGrantMaster: 'Master cannot be granted with a command',
        alreadyHasRole: 'The player already has this role',
        accountNotFound: 'Player account not found',
        setRoleUsage: '!setrole <#ID | AUTH> <{roles}> [time]',
        list: {
            usage: '!list <{roles}> [ID in the list] - optional, to view a player\'s profile',
            empty: '{role} LIST: empty.',
            header: '{role} LIST:',
            noSuchIndex: 'No such ID in the list'
        },
        liveUpdateNotice: 'Your role has been updated: {roleName}. Type !account for details'
    },

    ban: {
        usage: '!ban <#ID | AUTH> <time> [reason]',
        selfOrProtected: 'You cannot ban yourself or a player protected from bans',
        invalidId: 'Invalid ID entered',
        invalidTime: 'Time must be in the correct format (example: 10min)',
        roleTimeLimit: 'Your role has a ban duration limit: 30min max',
        success: '{admin} banned {target} for {time}{reason}.',
        reasonSuffix: ', reason: {reason}',
        timeSuffix: ' for {time}',
        kickMessage: '{admin} banned you for {time}{reason}\n discord: {discord}',
        kickMessageLive: '{admin} banned you{time}{reason}\n discord: {discord}',
        announceLive: '{admin} banned {target}{time}{reason}.',
        notFound: 'That identifier is not associated with a ban',
        unbanUsage: '!unban <ID | AUTH>',
        notFoundForUnban: 'That identifier is not associated with a ban',
        unbanned: '{admin} unbanned {target}',
        listEmpty: 'The ban list is empty.',
        listHeader: 'Ban list: {list}.',
        listEntry: '{name} ({mins}min) [{index}]'
    },

    mute: {
        usage: '!mute <#ID> <time> [reason]',
        invalidId: 'Invalid format',
        notInRoom: 'No player with that ID in the room',
        invalidTime: 'Time must be in the correct format (example: 10min)',
        roleTimeLimit: 'Your role has a mute duration limit: 1h max',
        protected: 'This player is protected from mutes.',
        success: '{admin} muted {target} for {time}{reason}.',
        reasonSuffix: ', reason: {reason}',
        timeSuffix: ' for {time}',
        stillMuted: 'You are muted: {mins}min (admins can still see your messages)',
        mutedChatEcho: '*MUTED* {name} ({id}): {message}',
        noLongerMuted: '{name} is no longer muted',
        canSpeak: 'You can speak again now.',
        unmuteUsage: '!unmute <#ID | ID (from mute list)>',
        notMuted: 'This player is not muted!',
        unmuted: '{admin} unmuted {target}!',
        listEmpty: 'The mute list is empty.',
        listHeader: 'Mute list: {list}.',
        listEntry: '{name} ({mins}min)[{id}]'
    },

    password: {
        cleared: 'Password has been cleared - {admin}',
        set: 'Room password is now: {password} - {admin}'
    },

    auth: {
        needPublicId: 'Error. You need to enter a public ID',
        alreadyInList: 'This public ID is already in the list',
        added: '{auth} was added to the authorized players list',
        notInList: 'This public ID is not in the list',
        removed: '{auth} was removed from the authorized players list',
        cleared: 'The authorized players list has been cleared',
        joinModeStatus: 'Authorized-players-only join is currently: {status}',
        joinModeOn: 'Authorized-players-only join enabled - {admin}',
        joinModeOff: 'Authorized-players-only join disabled - {admin}',
        invalidOption: 'Error. No such option: mode / on / off',
        statusOn: 'on',
        statusOff: 'off',
        kicked: 'Only authorized players can join right now\n discord: {discord}'
    },

    mode: {
        list: 'Available room modes: {list}.',
        invalidMode: 'Invalid mode name, use "!mode list" to see available room modes',
        alreadySet: 'This mode is already active',
        changed: 'Room mode is now: {mode}'
    },

    statsReset: {
        done: 'Stats have been reset (backup: {filename}, records: {count})'
    },

    matchPoint: {
        usage: 'Enter a number or "info"',
        info: 'The current game (if running) is to {value} points.',
        invalidNumber: 'Invalid number',
        changed: 'The game is now played to {value} points! This takes effect from the next game (if one is running).'
    },
    teamSize: {
        usage: 'Enter a number',
        invalidNumber: 'Invalid number',
        changed: 'Game mode is now {size}x{size}! This takes effect from the next game (if one is running).'
    },

    winstay: {
        status: 'Winstay mode is currently: {status}',
        statusOn: 'on',
        statusOff: 'off',
        enabled: 'Winstay mode enabled - {admin}',
        disabled: 'Winstay mode disabled - {admin}',
        invalidOption: 'Error. No such option: mode / on / off',
        streak: '🔥Win streak: {streak}'
    },
    teamPick: {
        status: 'Team forming mode is currently: {mode}',
        list: 'Available team forming modes: {list}.',
        invalidMode: 'Invalid mode. "!teampick list" — list of available modes',
        alreadySet: 'This mode is already active',
        changed: 'Team forming mode is now: {mode} — {admin}'
    },

    training: {
        onlyInPrivate: 'Training mode cannot be toggled manually in public mode',
        status: 'Training mode is currently: {status}',
        statusOn: 'on',
        statusOff: 'off',
        enabled: 'Training mode enabled - {admin}',
        disabled: 'Training mode disabled - {admin}',
        invalidOption: 'Error. No such option: mode / on / off'
    },
    ballSpawner: {
        disabledNotice: 'Training mode is off, this command cannot be used right now',
        info: 'Ball spawn settings: {status}\nYou can use a range instead of a number: min..max (example: !bs -450..-350 200 0.5..0.9 -11.9 3000)',
        infoOff: 'off',
        infoOn: '{descriptors} {interval} (x, y, xspeed, yspeed, interval)',
        turnedOff: 'Ball spawner turned off - {admin}',
        applied: 'Ball spawn settings: {descriptors} {interval} (x, y, xspeed, yspeed, interval) - {admin}',
        invalidArgs: 'Invalid arguments: x, y, xspeed, yspeed, interval(ms)\nNumber or a min..max range (example: -450..-350)',
        invalidInterval: 'Invalid interval, specify time in milliseconds, 1s=1000ms',
        notEnoughArgs: 'Not enough arguments: !bs x, y, xspeed, yspeed, interval(ms)\nYou can use a range instead of a number: min..max'
    },

    up: {
        roomCooldown: '!up is on cooldown for the whole room: {mins}min left',
        alreadyBooked: 'The next pick\'s captain slot is already booked by {name}',
        booked: '🌟 {name} booked the captain slot for the next team formation!',
        captainRed: '🌟 {name} became RED captain via !up booking!',
        captainBlue: '🌟 {name} became BLUE captain via !up booking!'
    },

    chatColor: {
        usage: 'Enter a color in HEX format: FFFFFF (that\'s white)',
        cleared: 'Chat color has been turned off!',
        set: 'You now have this chat color! \nTo turn off colored chat: !color clear'
    },

    stats: {
        selfEmpty: 'You have no stats yet — play at least one game!',
        targetOffline: 'The player must be on the server for you to view their stats',
        invalidArg: 'Invalid parameter, enter a player ID if they are on the server, or their @nickname',
        nameNotFound: 'No player with that name found in stats',
        needIndex: '{count} players found with that name in stats, run the command again but add the number you need after the name\nHere are their names from the deanon command:\n{names}',
        indexEntry: '{index}) {names}',
        notInStats: 'This player has no stats, they must play at least one game!',
        line: '📊{name} - Games: {games}, Wins: {wins} ({winRate}%), Goals: {goals}, POB: {pob}% (of {goalsPlusBlocked}), Blocks: {blocks}, Assists: {assists}, Errors: {errors} ({errPerGame}/game), Serves: {serves}, Aces: {aces} ({aceRate}%), Time: {time}\nPOB - Percentage Of Blocks beaten (the lower it is, the more of your attacks got blocked)'
    },

    rename: {
        failed: 'Error!',
        success: 'You successfully renamed yourself to {name}!'
    },

    tops: {
        invalidTop: 'Invalid leaderboard: {list}\nExample - !tops <board> <count> / !tops all <count> - to show all leaderboards',
        invalidLength: 'Invalid leaderboard length, min: 5 max: 50',
        notEnoughPlayers: 'Not enough players for the leaderboard: {missing} more needed',
        line: '{statName} - {entries}',
        entry: '{index}. {name} ({value})'
    },

    getAuth: {
        self: '{name} ID: {auth}',
        usage: 'Invalid format! ("!getauth #ID")',
        notFound: 'No player with that ID exists',
        target: '{name} ID: {auth}'
    },

    queue: {
        empty: '📝The queue is empty',
        header: '📝Queue (player [missed games]): {list}.',
        vipHeader: '🌟VIP queue (player [missed games]): {list}.',
        vipEmpty: '🌟The VIP queue is empty',
        entry: '{name} [{missed}]'
    },

    discordLink: {
        info: 'Our discord: {discord}',
        alreadyLinked: 'Your Discord is already linked to this account. To link a different one, first unlink the current one with !discordunlink',
        success: '✅ Discord successfully linked to your account!',
        invalidCode: 'The code is invalid or expired. Get a new one with /link in Discord',
        alreadyLinkedAccount: 'Your HaxBall account is already linked to Discord',
        alreadyLinkedElsewhere: 'This Discord account is already linked to another account',
        unknownAccount: 'Your HaxBall account was not found',
        unavailable: 'Discord integration is currently unavailable, try again later',
        genericFail: 'Failed to link Discord',
        unlink: {
            adminOnly: 'Only ADMIN and above can unlink someone else\'s Discord',
            usage: 'Invalid format: !discordunlink <#ID | AUTH>',
            targetNotFound: 'No player with that ID on the server',
            success: '✅ Discord unlinked from account {target}',
            notLinked: 'Account {target} is not linked to Discord'
        }
    },

    telegram: {
        info: 'My telegram: {telegram}'
    },

    afk: {
        entered: '💤{name} is now AFK',
        left: '🐣{name} is no longer AFK',
        listEmpty: '💤No one is on the AFK list',
        listHeader: '💤AFK list: {list}.',
        listEntry: '{name} ({mins}min)',
        forcedToSpectate: '{name} is AFK!'
    },

    ids: {
        header: '📑player (id): {list}.',
        entry: '{name} ({id})'
    },

    deanon: {
        usage: 'Enter a player ID',
        notFound: 'Player is not on the server',
        noNicknames: 'Error, could not look up this player\'s names',
        result: '🔍{name} is also known as: {names}.'
    },

    myPoint: {
        onlyInGame: 'This command can only be used on the field',
        coords: 'x: {x} y: {y}'
    },

    account: {
        adminOnly: 'Only ADMIN and above can view other accounts',
        invalidFormat: 'Invalid format: !account <#ID | AUTH>',
        playerOffline: 'No player with that ID is on the server. If they are offline, use their AUTH (43 characters).',
        notFound: 'Account not found',
        notFoundOwn: 'Your account was not found',
        view: '📋{nickname}:\npublic_id: {auth}\nrole: {role}\nuntil: {until}\ndiscord: {discord}',
        untilPermanent: 'permanent',
        discordUnlinked: 'not linked'
    },

    help: {
        list: 'Commands available to you: {list}.'
    },

    serve: {
        useTrainingCommand: 'To practice serves in training mode use !bs serve_red or !bs serve_blue',
        mustBeOnField: 'You must be on the field to serve',
        notEnoughPlayers: 'Not enough players on the field for a power serve',
        cannotServeNow: 'You cannot serve right now',
        someoneServing: 'Someone is already serving',
        notYourServe: 'It\'s not your serve right now'
    },

    chat: {
        unknownCommand: 'The command you tried does not exist for you. Type \'!help\' to see the available commands.',
        teamMessage: '{emoji} [TEAM] {name}: {message}',
        message: '{displayName}: {message}',
        messageWithId: '{displayName} ({id}): {message}'
    },

    bb: {
        farewell: 'Bye!'
    },

    game: {
        goal: {
            withAssist: '({assist})',
            block: 'blocked {blocked}\'s hit',
            ace: 'scored an ACE off the serve',
            scoreLine: '{time} {emoji} {scorer} {action} | {score}',
            counterScoreLine: '{time} {text} | {score}',
            counterBlock: '⚔️ {scorer} broke through {blocked}\'s block',
            counterAce: '🥏 {scorer} scored an ACE off the serve',
            ownGoal: '🐔 {scorer}{assist}',
            foul: '{time} 📛 {team} foul | {score}',
            teamRed: 'blue\'s',
            teamBlue: 'red\'s'
        },
        matchPointTied: '🎯Tied score, the game continues to {value} points',
        matchPoint: '🔥Match point for {team}',
        teamRed: 'red',
        teamBlue: 'blue',
        serveHint: 'Type "!serve" or "!sr" to make a power serve',
        powerServe: '🥏Power serve: {name}',
        block: '🛡️Block: {name}',
        doubleTouch: '📛Double touch: {name}',
        fourTouches: '📛4 touches: {team}',
        saveBall: '✳️Save ball',
        result: {
            redWin: '🏆Red team wins',
            draw: '💤Draw',
            blueWin: '🏆Blue team wins'
        },
        replay: '💾replay: № {id} | download: {discord}',
        timeout: '⌚️ The game will start in {seconds} seconds.',
        notEnoughPlayers: '⛔️ Not enough players to start a match.'
    },

    captains: {
        pickPrompt: 'Pick a player: {list}\nType their number in chat to pick them.',
        picked: '{captain} picked {chosen}',
        noSuchNumber: 'No such number in the list!',
        turnAnnounce: '🧢 Captain {captain}\'s turn',
        timeWarning: '⏳ 4 seconds left to pick!',
        timeUp: '⏰ Time\'s up — {name} was picked at random',
        randomizing: '⚖️ Randomizing teams...'
    },

    join: {
        alreadyOnline: 'Looks like you\'re already in the room',
        banned: 'You are banned: {mins} min\n discord: {discord}',
        authOnly: 'Only authorized players can join right now\n discord: {discord}',
        announceAdmin: '💥 {roleName} {name} joined the room!',
        announceVip: '🌟 {roleName} {name} joined the room!',
        announcePreadmin: '💢 {roleName} {name} joined the room!',
        welcome: 'Join our discord server: {discord}\nFollow my telegram: {telegram}\nType "!help" to see the list of available commands.\nPrefix your message with "t" to write to team chat\nFor any questions, tg: {contactTelegram}',
        leaveIdEcho: '{name} ID: {auth}',
        wentInGame: '@{name} you\'re in the game!'
    },

    promo: {
        discordAndTelegram: 'Join our Discord server: {discord}\nFollow my Telegram: {telegram}',
        vipInfo: 'Our room has a VIP perk!\nFeatures, price and other details on our Discord server: {discord}',
        linkDiscord: 'Join our Discord server and link your Discord profile to your HaxBall account!\nJust type /link in any server chat.\n{discord}'
    },

    intervals: {
        inactivityWarning: '⛔️If you don\'t show signs of life within {seconds}sec, you will be kicked',
        vipPasswordConsoleLine: '[{date}] 🌟New VIP password: {password}'
    },

    discordBot: {
        roomOnlineLog: '**[{date}] ROOM ONLINE**',
        vipPasswordHeader: '# {prefix}🌟VIP password: {password}',
        statsBackupUploaded: '{prefix}📦 Stats backup before reset',
        onlineEmbed: {
            playersField: 'PLAYERS:',
            footer: 'updated once per minute, latest update: {date}',
            joinButton: 'Join'
        },
        report: {
            mute: 'muted',
            ban: 'banned',
            unmute: 'unmuted',
            unban: 'unbanned',
            line: '## {prefix}🔴 {admin} {action} {target}{time}{reason}',
            timeSuffix: ' for {time}',
            reasonSuffix: ', reason: {reason}'
        },
        linkSlash: {
            alreadyLinked: '❌ Your Discord is already linked to a HaxBall account. To link a different one, unlink the current one first with `/unlink`.',
            codeReply: '🔗 Your link code: **{code}**\nType this in HaxBall: `!discord {code}`\nCode is valid for 10 minutes.',
            unlinked: '✅ Discord unlinked from your HaxBall account.',
            notLinked: '❌ Your Discord is not linked to any HaxBall account.'
        }
    },

    discord: {
        command: {
            setRole: '[MASTER] Grant a role to a player', publicId: 'Player public_id (43 characters)', newRole: 'New role',
            roleTime: 'Role duration, e.g. 30d (empty = permanent)', roleList: '[MASTER] List players with a role',
            role: 'Role', password: '[MASTER] Set/reset a room password', room: 'Room',
            passwordValue: 'New password (empty = reset)', statsClear: '[MASTER] Reset all stats (with backup)',
            statsBackup: '[MASTER] Back up stats without resetting', ban: '[ADMIN] Ban a player',
            banTime: 'Ban duration, e.g. 10min / 1d', reason: 'Reason', unban: '[ADMIN] Unban a player',
            mute: '[ADMIN] Mute a player', muteTime: 'Mute duration, e.g. 10min / 1h', unmute: '[ADMIN] Unmute a player',
            bans: '[ADMIN] List bans', mutes: '[ADMIN] List mutes', tops: 'Player leaderboard by statistic',
            stat: 'Statistic (or "all" for all leaderboards)', count: 'Number of rows (5-50, default 10)',
            stats: 'Player statistics', nickname: 'Player nickname (empty = yourself)', index: 'List index, if multiple nicknames exist',
            account: 'Account information', accountPublicId: 'Player public_id (empty = yourself, ADMIN required for others)',
            link: 'Get a code to link Discord to a HaxBall account', unlink: 'Unlink your Discord from HaxBall'
        },
        notLinkedTitle: 'Discord not linked',
        notLinkedBody: 'Use `/link`, then `!discord <code>` in the room, to link your HaxBall account.',
        insufficientRoleTitle: 'Insufficient permissions',
        insufficientRoleBody: 'Requires **{role}** role or above, you have **{yourRole}**.',
        invalidPublicIdTitle: 'Invalid public_id',
        invalidPublicIdBody: 'public_id must be a 43-character string.',
        invalidTimeTitle: 'Invalid time format',
        invalidTimeBody: 'Example: `{example}`.',

        setRole: {
            selfTitle: 'Invalid action',
            selfBody: 'You cannot change your own role.',
            notFoundTitle: 'Account not found',
            notFoundBody: 'No account found with that public_id.',
            successTitle: 'Role updated',
            successBody: '{identity}\nis now **{role}**{until}.',
            untilTimed: ' until <t:{timestamp}:f>',
            untilPermanent: ' (permanent)'
        },
        getRoleList: {
            empty: 'Empty.',
            title: '📋 {role} — {count}',
            entry: '**{index}.** {identity}'
        },
        password: {
            roomUnavailableTitle: 'Room unavailable',
            roomUnavailableBody: 'Room **{room}** is not currently running.',
            successTitle: 'Password updated',
            successSet: 'Room **{room}**\nnew password: `{value}`',
            successCleared: 'Room **{room}**\npassword cleared.'
        },
        statsClear: {
            successTitle: 'Stats reset',
            successBody: 'Backup: `{filename}`\nrecords: {count}'
        },
        statsBackup: {
            successTitle: 'Stats backup created',
            successBody: 'File: `{filename}`\nrecords: {count}'
        },
        ban: {
            selfOrProtectedTitle: 'Invalid action',
            selfOrProtectedBody: 'You cannot ban yourself or a player protected from bans.',
            successTitle: 'Player banned',
            successBody: '{identity}\nfor **{time}**{reason}\n{liveStatus}',
            liveKicked: '🔴 Was in the room — kicked immediately.',
            liveOffline: 'Not in the room — the ban will apply on their next join.'
        },
        unban: {
            notFoundTitle: 'Not found',
            notFoundBody: 'This public_id was not found in the ban list.',
            successTitle: 'Player unbanned'
        },
        mute: {
            protectedTitle: 'Invalid action',
            protectedBody: 'This player is protected from mutes.',
            successTitle: 'Player muted',
            successBody: '{identity}\nfor **{time}**{reason}\n{liveStatus}',
            liveApplied: '🔴 Was in the room — applied immediately.',
            liveOffline: 'Not in the room — the mute will apply on their next join.'
        },
        unmute: {
            notFoundTitle: 'Not found',
            notFoundBody: 'This player is not muted.',
            successTitle: 'Player unmuted',
            liveApplied: '\nApplied immediately.'
        },
        bans: {
            title: '📋 Ban list — {count}',
            empty: 'Empty.',
            entry: '**{index}.** {identity}\nremaining: {mins}m'
        },
        mutes: {
            title: '📋 Mute list — {count}',
            empty: 'Empty.',
            entry: '**{index}.** {identity}\nremaining: {mins}m'
        },
        tops: {
            notEnoughDataTitle: 'Not enough data',
            notEnoughDataBody: 'Not enough players for the leaderboard: {missing} more needed.',
            allTitle: '📊 Player leaderboards',
            statTitle: '📊 Top: {stat}',
            sectionHeader: '**🏆 Top by {stat}**\n{lines}',
            line: '`{index}.` **{name}** — {value}'
        },
        stats: {
            notFoundTitle: 'Not found',
            multipleFoundTitle: '{count} players found with nickname "{nickname}"',
            multipleFoundBody: '{choices}\n\nRe-run the command with the `index` argument to pick the right one.',
            choiceEntry: '[{index}] {name} ({auth}) - {games} games',
            emptyTitle: 'Stats not found',
            emptyBody: 'Must play at least one game.'
        },
        account: {
            adminOnlyTitle: 'Insufficient permissions',
            adminOnlyBody: 'Only ADMIN and above can view other accounts.',
            notFoundTitle: 'Account not found',
            title: '📋 {nickname}',
            body: '{identity}\n**role:** {role}\n**until:** {until}\n**discord:** {discord}',
            untilPermanent: 'permanent',
            discordUnlinked: 'not linked'
        },
        genericErrorTitle: 'Error',
        genericErrorBody: 'An error occurred while running the command.',

        statsFields: {
            games: '**Games:** {value}',
            wins: '**Wins:** {value} ({rate}%)',
            goals: '**Goals:** {value}',
            pob: '**POB:** {value}% (of {total})',
            blocks: '**Blocks:** {value}',
            assists: '**Assists:** {value}',
            errors: '**Errors:** {value} ({perGame}/game)',
            serves: '**Serves:** {value}',
            aces: '**Aces:** {value} ({rate}%)',
            time: '**Time:** {hours}h'
        }
    }
};