/*
 * Default (Russian) dictionary. Covers every string the bot ever shows
 * to a player, in the HaxBall room and in Discord.
 *
 * Do NOT edit this file to get a different language. Instead, copy it
 * to locale/<code>.js (e.g. locale/de.js), translate the string values
 * only — keep every key path identical — register it in dicts inside
 * index.js, and point LOCALE=<code> at it via .env / roomConstants. This
 * keeps ru.js as a stable reference translation that other locale files
 * can safely fall back to for any key they haven't translated yet (see
 * index.js for the fallback mechanism).
 *
 * commands.js (the command/alias registry) is intentionally not covered
 * here — command aliases are treated as configuration, not translatable
 * text.
 */
module.exports = {
    common: {
        error: 'Ошибка',
        invalidNumber: 'Некорректное число',
        invalidFormat: 'Неверный формат',
        notEnoughArgs: 'Недостаточно аргументов: {usage}',
        wrongArgsCount: 'Неверное количество аргументов: {usage}',
        playerNotFound: 'Игрока с таким ID нет на сервере',
        playerNotOnServer: 'Игрока нет на сервере',
        accountNotFound: 'Аккаунт не найден',
        accountNotFoundOwn: 'Ваш аккаунт не найден',
        unknown: 'неизвестно',
        none: '—',
        discordTokenMissing: '[Discord] DISCORD_BOT_TOKEN не задан, Discord-интеграция отключена.'
    },

    time: {
        units: {
            s: 'сек',
            min: 'мин',
            h: 'ч',
            d: 'дн',
            w: 'нед',
            mon: 'мес'
        }
    },

    role: {
        names: {
            master: 'Создатель',
            admin: 'Администратор',
            preadmin: 'Мл. Администратор',
            vip: 'VIP',
            player: 'игрок'
        },
        labels: {
            master: 'MASTER',
            admin: 'ADMIN',
            preadmin: 'PREADMIN',
            vip: 'VIP',
            player: 'PLAYER'
        },
        expired: 'Срок вашей роли истёк =(',
        updated: '{displayName} теперь {roleName}{timeStr}!',
        updatedTimed: ' на {timeStr}',
        noSuchRole: 'Некоректная роль: {roles}',
        cannotSetSelf: 'Вы не можете менять роль себе!',
        cannotGrantMaster: 'Нельзя выдать мастера командой',
        alreadyHasRole: 'У игрока и так эта роль',
        accountNotFound: 'Аккаунт игрока не найден',
        setRoleUsage: '!setrole <#ID | AUTH> <{roles}> [время]',
        list: {
            usage: '!list <{roles}> [ID в списке] - чтобы посмотреть профиль игрока, необязательный аргумент',
            empty: '{role} LIST: пусто.',
            header: '{role} LIST:',
            noSuchIndex: 'Такого айди нет в списке'
        },
        liveUpdateNotice: 'Ваша роль была обновлена: {roleName}. Для подробной информации введите !account'
    },

    ban: {
        usage: '!ban <#ID | AUTH> <time> [причина]',
        selfOrProtected: 'Вы не можете забанить себя или у этого игрока защита от бана',
        invalidId: 'Введен неверный ID',
        invalidTime: 'Нужно написать время в правильном формате (пример: 10min)',
        roleTimeLimit: 'У вашей роли ограничение на время бана: максимум 30min',
        success: '{admin} забанил {target} на {time}{reason}.',
        reasonSuffix: ' по причине: {reason}',
        timeSuffix: ' на {time}',
        kickMessage: '{admin} забанил вас на {time}{reason}\n discord: {discord}',
        kickMessageLive: '{admin} забанил вас{time}{reason}\n discord: {discord}',
        announceLive: '{admin} забанил {target}{time}{reason}.',
        notFound: 'Введенный вами идентификатор не связан с баном',
        unbanUsage: '!unban <ID | AUTH>',
        notFoundForUnban: 'Введенный вами идентификатор не связан с баном',
        unbanned: '{admin} разбанил {target}',
        listEmpty: 'Никого нет в бан-листе.',
        listHeader: 'Бан-лист: {list}.',
        listEntry: '{name} ({mins}мин) [{index}]'
    },

    mute: {
        usage: '!mute <#ID> <время> [причина]',
        invalidId: 'Неверный формат',
        notInRoom: 'Игрока с таким ID в руме нет',
        invalidTime: 'Нужно написать время в правильном формате (пример: 10min)',
        roleTimeLimit: 'У вашей роли ограничение на время мута: максимум 1h (1 час)',
        protected: 'У игрока защита от мута.',
        success: '{admin} замутил {target} на {time}{reason}.',
        reasonSuffix: ' по причине: {reason}',
        timeSuffix: ' на {time}',
        stillMuted: 'Вы в муте: {mins}мин (ваши сообщения видят админы)',
        mutedChatEcho: '*MUTED* {name} ({id}): {message}',
        noLongerMuted: '{name} больше не в муте',
        canSpeak: 'Теперь ты можешь говорить.',
        unmuteUsage: '!unmute <#ID| ID(из мут списка)>',
        notMuted: 'Этот игрок не в муте!',
        unmuted: '{admin} размутил {target}!',
        listEmpty: 'В мут-листе пусто.',
        listHeader: 'Мут-лист: {list}.',
        listEntry: '{name} ({mins}мин)[{id}]'
    },

    password: {
        cleared: 'Пароль был сброшен - {admin}',
        set: 'Теперь пароль от комнаты: {password} - {admin}'
    },

    auth: {
        needPublicId: 'Ошибка. Нужно написать паблик айди',
        alreadyInList: 'Этот паблик уже в списке',
        added: '{auth} был добавлен в список авторизированных игроков',
        notInList: 'Этого паблика нет в списке',
        removed: '{auth} был удалён из списка авторизированных игроков',
        cleared: 'Список авторизированных игроков был очищен',
        joinModeStatus: 'Сейчас вход только авторизированных игроков: {status}',
        joinModeOn: 'Вход только авторизированых игроков включён - {admin}',
        joinModeOff: 'Вход только авторизированых игроков выключен - {admin}',
        invalidOption: 'Ошибка. Такого варианта не существует: mode / on / off',
        statusOn: 'включён',
        statusOff: 'выключен',
        kicked: 'Сейчас в комнату могут зайти только авторизованные игроки\n discord: {discord}'
    },

    mode: {
        list: 'Список модов работы комнаты: {list}.',
        invalidMode: 'Некорректное название мода, "!mode list" - чтобы узнать список доступных модов комнаты',
        alreadySet: 'Этот мод уже стоит',
        changed: 'Теперь мод комнаты: {mode}'
    },

    statsReset: {
        done: 'Статистика была сброшена (бекап: {filename}, записей: {count})'
    },

    matchPoint: {
        usage: 'Напишите число или "info"',
        info: 'Текущая игра (если идёт) до {value} мячей.',
        invalidNumber: 'Некорректное число',
        changed: 'Теперь игра идёт до {value} мячей! Изменения войдут в силу со следующей игры (если текущая идёт).'
    },
    teamSize: {
        usage: 'Напишите число',
        invalidNumber: 'Некорректное число',
        changed: 'Теперь режим игры {size}x{size}! Изменения войдут в силу со следующей игры (если текущая идёт).'
    },

    winstay: {
        status: 'Сейчас режим winstay: {status}',
        statusOn: 'включён',
        statusOff: 'выключен',
        enabled: 'Режим winstay включён - {admin}',
        disabled: 'Режим winstay выключен - {admin}',
        invalidOption: 'Ошибка. Такого варианта нет: mode / on / off',
        streak: '🔥Серия побед: {streak}'
    },
    teamPick: {
        status: 'Сейчас распределение команд: {mode}',
        list: 'Список режимов распределения команд: {list}.',
        invalidMode: 'Некорректный режим. "!teampick list" — список доступных режимов',
        alreadySet: 'Этот режим уже стоит',
        changed: 'Теперь распределение команд: {mode} — {admin}'
    },

    training: {
        onlyInPrivate: 'При public моде нельзя включать режим тренировки вручную',
        status: 'Сейчас режим тренировки: {status}',
        statusOn: 'включён',
        statusOff: 'выключен',
        enabled: 'Режим тренировки включён - {admin}',
        disabled: 'Режим тренировки выключен - {admin}',
        invalidOption: 'Ошибка. Такого варианта нет: mode / on / off'
    },
    ballSpawner: {
        disabledNotice: 'Режим тренировки выключен, сейчас нельзя использовать эту команду',
        info: 'Настройки спавна мяча: {status}\nМожно указывать диапазон вместо числа: min..max (пример: !bs -450..-350 200 0.5..0.9 -11.9 3000)',
        infoOff: 'выключен',
        infoOn: '{descriptors} {interval} (x, y, xspeed, yspeed, interval)',
        turnedOff: 'Спавн мяча выключен - {admin}',
        applied: 'Настройки спавна мяча: {descriptors} {interval} (x, y, xspeed, yspeed, interval) - {admin}',
        invalidArgs: 'Некорректный вид аргументов: x, y, xspeed, yspeed, interval(мс)\nЧисло или диапазон min..max (пример: -450..-350)',
        invalidInterval: 'Некорректный интервал, укажите время в милисекундах 1с=1000мс',
        notEnoughArgs: 'Недостаточно аргументов: !bs x, y, xspeed, yspeed, interval(мс)\nМожно указывать диапазон вместо числа: min..max'
    },

    up: {
        roomCooldown: 'Команда !up сейчас на КД для всей комнаты: ещё {mins}мин',
        alreadyBooked: 'Место капитана на следующем пике уже забронировано игроком {name}',
        booked: '🌟 {name} забронировал место капитана на следующем формировании команд!',
        captainRed: '🌟 {name} стал капитаном КРАСНЫХ по брони !up!',
        captainBlue: '🌟 {name} стал капитаном СИНИХ по брони !up!'
    },

    chatColor: {
        usage: 'Нужно написать цвет в HEX формате: FFFFFF (это белый)',
        cleared: 'Цвет чата был выключен!',
        set: 'Теперь у вас вот такой цвет чата! \nВыключить цветной чат: !color clear'
    },

    stats: {
        selfEmpty: 'Вас нет в статистике сыграйте хотя бы одну игру!',
        targetOffline: 'Игрок должен быть на сервере, чтобы вы могли посмотреть его статистику',
        invalidArg: 'Некорректный параметр, введите айди игрока если он на сервере или его @никнейм',
        nameNotFound: 'Игрока с таким именем нет в статистике',
        needIndex: 'Игроков с таким именем в статистике {count}, введите команду ещё раз, но после имени введите номер нужного вам\nВот их имена из deanon команды:\n{names}',
        indexEntry: '{index}) {names}',
        notInStats: 'Игрока нет в статистике он должен сыграть хотя бы одну игру!',
        line: '📊{name} - Игры: {games}, Победы: {wins} ({winRate}%), Голы: {goals}, ПОБ: {pob}% (из {goalsPlusBlocked}), Блоки: {blocks}, Пасы: {assists}, Ошибки: {errors} ({errPerGame}/игра), Подачи: {serves}, ЭЙСы: {aces} ({aceRate}%), Время: {time}\nПОБ - Процент Обойдённых Блоков (чем ниже процент, тем больше ваших атак было заблокированно)'
    },

    rename: {
        failed: 'Ошибка!',
        success: 'Вы успешно переименовали себя {name} !'
    },

    tops: {
        invalidTop: 'Некорректный топ: {list}\nПример - !tops <топ> <кол-во> / !tops all <кол-во> - чтобы вывести все топы',
        invalidLength: 'Некорректная длина топа, min: 5 max: 50',
        notEnoughPlayers: 'Недостаточно игроков в топе: ещё {missing}',
        line: '{statName} - {entries}',
        entry: '{index}. {name} ({value})'
    },

    getAuth: {
        self: '{name} ID: {auth}',
        usage: 'Неверный формат! ("!getauth #ID")',
        notFound: 'Игрока с таким ID не существует',
        target: '{name} ID: {auth}'
    },

    queue: {
        empty: '📝В очереди никого нет',
        header: '📝Очередь (игрок [пропущ. игр]): {list}.',
        vipHeader: '🌟VIP-Очередь (игрок [пропущ. игр]): {list}.',
        vipEmpty: '🌟В VIP-Очереди никого нет',
        entry: '{name} [{missed}]'
    },

    discordLink: {
        info: 'Наш discord: {discord}',
        alreadyLinked: 'Ваш Discord уже привязан к этому аккаунту. Чтобы привязать другой, сначала отвяжите текущий командой !discordunlink',
        success: '✅ Discord успешно привязан к вашему аккаунту!',
        invalidCode: 'Код неверный или истёк. Получите новый командой /link в Discord',
        alreadyLinkedAccount: 'Ваш аккаунт HaxBall уже привязан к Discord',
        alreadyLinkedElsewhere: 'Этот Discord уже привязан к другому аккаунту',
        unknownAccount: 'Ваш аккаунт HaxBall не найден',
        unavailable: 'Discord-интеграция сейчас недоступна, попробуйте позже',
        genericFail: 'Не удалось привязать Discord',
        unlink: {
            adminOnly: 'Отвязать чужой Discord могут только ADMIN и выше',
            usage: 'Некорректный формат: !discordunlink <#ID | AUTH>',
            targetNotFound: 'Игрока с таким ID нет на сервере',
            success: '✅ Discord отвязан от аккаунта {target}',
            notLinked: 'Аккаунт {target} не привязан к Discord'
        }
    },

    telegram: {
        info: 'Мой telegram: {telegram}'
    },

    afk: {
        entered: '💤{name} теперь АФК',
        left: '🐣{name} больше не АФК',
        listEmpty: '💤В списке АФК никого нет',
        listHeader: '💤Список АФК: {list}.',
        listEntry: '{name} ({mins}мин)',
        forcedToSpectate: '{name} АФК!',
        afkKick: 'АФК'
    },

    ids: {
        header: '📑player (id): {list}.',
        entry: '{name} ({id})'
    },

    deanon: {
        usage: 'Напишите айди игрока',
        notFound: 'Игрока нет на сервере',
        noNicknames: 'Ошибка, невозможно узнать имена игрока',
        result: '🔍{name} также известен как: {names}.'
    },

    myPoint: {
        onlyInGame: 'Команду можно использовать только на поле',
        coords: 'x: {x} y: {y}'
    },

    account: {
        adminOnly: 'Смотреть чужие аккаунты могут только ADMIN и выше',
        invalidFormat: 'Некорректный формат: !account <#ID | AUTH>',
        playerOffline: 'Игрока с таким ID нет на сервере. Если он оффлайн, используйте его AUTH (43 символа).',
        notFound: 'Аккаунт не найден',
        notFoundOwn: 'Ваш аккаунт не найден',
        view: '📋{nickname}:\npublic_id: {auth}\nроль: {role}\nдо: {until}\ndiscord: {discord}',
        untilPermanent: 'бессрочно',
        discordUnlinked: 'не привязан'
    },

    help: {
        list: 'Доступные вам команды: {list}.'
    },

    serve: {
        useTrainingCommand: 'Чтобы тренировать подачу в тренинг моде используй !bs serve_red или !bs serve_blue',
        mustBeOnField: 'Вы должны быть в игре, чтобы сделать подачу',
        notEnoughPlayers: 'Недостаточно игроков на поле для силовой подачи',
        cannotServeNow: 'Сейчас нельзя сделать подачу',
        someoneServing: 'Кто-то уже делает подачу',
        notYourServe: 'Сейчас не ваша подача'
    },

    chat: {
        unknownCommand: 'Команда, которую вы пытались ввести, для вас не существует. Пожалуйста, введите \'!help\', чтобы получить доступные команды.',
        teamMessage: '{emoji} [TEAM] {name}: {message}',
        message: '{displayName}: {message}',
        messageWithId: '{displayName} ({id}): {message}'
    },

    bb: {
        farewell: 'Пока!'
    },

    game: {
        goal: {
            withAssist: '({assist})',
            block: 'блокировал удар {blocked}',
            ace: 'сделал ЭЙС с подачи',
            scoreLine: '{time} {emoji} {scorer} {action} | {score}',
            counterScoreLine: '{time} {text} | {score}',
            counterBlock: '⚔️ {scorer} пробил блок {blocked}',
            counterAce: '🥏 {scorer} сделал ЭЙС с подачи',
            ownGoal: '🐔 {scorer}{assist}',
            foul: '{time} 📛 Фол {team} | {score}',
            teamRed: 'синих',
            teamBlue: 'красных'
        },
        matchPointTied: '🎯Счёт равный, игра продолжится до {value} мячей',
        matchPoint: '🔥Матч поинт {team}',
        teamRed: 'красных',
        teamBlue: 'синих',
        serveHint: 'Напиши "!serve" или "!sr", чтобы подать силовую подачу',
        powerServe: '🥏Силовая подача: {name}',
        block: '🛡️Блок: {name}',
        doubleTouch: '📛Двойное касание: {name}',
        fourTouches: '📛4 касания: {team}',
        saveBall: '✳️Сейв-мяч',
        result: {
            redWin: '🏆Победа красной команды',
            draw: '💤Ничья',
            blueWin: '🏆Победа синей команды'
        },
        replay: '💾replay: № {id} | скачать: {discord}',
        timeout: '⌚️ Игра начнётся через {seconds} секунд.',
        notEnoughPlayers: '⛔️ Недостаточно игроков, чтобы начать матч.'
    },

    captains: {
        pickPrompt: 'Выберите игрока: {list}\nДля выбора игрока напишите его номер в чат.',
        picked: '{captain} выбрал {chosen}',
        noSuchNumber: 'Такого номера нет в списке!',
        turnAnnounce: '🧢 Ход капитана {captain}',
        timeWarning: '⏳ Осталось 4 секунды для выбора!',
        timeUp: '⏰ Время вышло — случайно выбран {name}',
        randomizing: '⚖️ Рандомизация команд...'
    },

    join: {
        alreadyOnline: 'Кажется ты уже есть в комнате',
        banned: 'Вы забанены: {mins} мин\n discord: {discord}',
        authOnly: 'Сейчас в комнату могут зайти только авторизованные игроки\n discord: {discord}',
        announceAdmin: '💥 {roleName} {name} зашёл на комнату!',
        announceVip: '🌟 {roleName} {name} зашёл на комнату!',
        announcePreadmin: '💢 {roleName} {name} зашёл на комнату!',
        welcome: 'Заходи на наш discord-сервер: {discord}\nПодписывайся на мой telegram: {telegram}\nНапиши "!help" чтобы узнать список доступных команд.\nНапиши перед сообщением "ч", чтобы писать в чат команды\nПо всем вопросам tg: {contactTelegram}',
        leaveIdEcho: '{name} ID: {auth}',
        wentInGame: '@{name} ты в игре!'
    },

    promo: {
        discordAndTelegram: 'Заходи на наш Discord-сервер: {discord}\nПодписывайся на мой Telegram: {telegram}',
        vipInfo: 'На нашей комнате есть привилегия VIP!\nВозможности, цена и другие подробности на нашем Discord-сервере: {discord}',
        linkDiscord: 'Заходи на наш Discord-сервер и привяжи свой Discord-профиль к аккаунту HaxBall!\nПросто напиши команду /link в любом чате сервера.\n{discord}'
    },

    intervals: {
        inactivityWarning: '⛔️Если ты не проявишь признаки жизни в течении {seconds}сек, ты будешь кикнут',
        vipPasswordConsoleLine: '[{date}] 🌟Новый VIP-Пароль: {password}'
    },

    discordBot: {
        roomOnlineLog: '**[{date}] ROOM ONLINE**',
        vipPasswordHeader: '# {prefix}🌟VIP-Пароль: {password}',
        statsBackupUploaded: '{prefix}📦 Бекап статистики перед сбросом',
        onlineEmbed: {
            playersField: 'PLAYERS:',
            footer: 'updated once per minute, latest update: {date}',
            joinButton: 'Присоединиться'
        },
        report: {
            mute: 'замутил',
            ban: 'забанил',
            unmute: 'размутил',
            unban: 'разбанил',
            line: '## {prefix}🔴 {admin} {action} {target}{time}{reason}',
            timeSuffix: ' на {time}',
            reasonSuffix: ' по причине: {reason}'
        },
        linkSlash: {
            alreadyLinked: '❌ Ваш Discord уже привязан к аккаунту HaxBall. Чтобы привязать другой, сначала отвяжите текущий командой `/unlink`.',
            codeReply: '🔗 Ваш код привязки: **{code}**\nВведите в HaxBall команду: `!discord {code}`\nКод действует 10 минут.',
            unlinked: '✅ Discord отвязан от аккаунта HaxBall.',
            notLinked: '❌ Ваш Discord не привязан ни к одному аккаунту HaxBall.'
        }
    },

    discord: {
        command: {
            setRole: '[MASTER] Выдать роль игроку', publicId: 'public_id игрока (43 символа)', newRole: 'Новая роль',
            roleTime: 'Время действия роли, напр. 30d (пусто = бессрочно)', roleList: '[MASTER] Список игроков с заданной ролью',
            role: 'Роль', password: '[MASTER] Установить/сбросить пароль комнаты', room: 'Комната',
            passwordValue: 'Новый пароль (пусто = сбросить)', statsClear: '[MASTER] Сбросить всю статистику (с бекапом)',
            statsBackup: '[MASTER] Сделать бекап статистики без сброса', ban: '[ADMIN] Забанить игрока',
            banTime: 'Время бана, напр. 10min / 1d', reason: 'Причина', unban: '[ADMIN] Разбанить игрока',
            mute: '[ADMIN] Замутить игрока', muteTime: 'Время мута, напр. 10min / 1h', unmute: '[ADMIN] Размутить игрока',
            bans: '[ADMIN] Список банов', mutes: '[ADMIN] Список мутов', tops: 'Топ игроков по показателю',
            stat: 'Показатель (или "all" — сразу все топы)', count: 'Сколько строк (5-50, по умолчанию 10)',
            stats: 'Статистика игрока', nickname: 'Ник игрока (пусто = вы сами)', index: 'Номер из списка, если ников несколько',
            account: 'Информация об аккаунте', accountPublicId: 'public_id игрока (пусто = вы сами, требуется ADMIN для чужих)',
            link: 'Получить код для привязки Discord к аккаунту HaxBall', unlink: 'Отвязать ваш Discord от аккаунта HaxBall'
        },
        notLinkedTitle: 'Discord не привязан',
        notLinkedBody: 'Используйте `/link`, затем `!discord <код>` в комнате, чтобы привязать аккаунт HaxBall.',
        insufficientRoleTitle: 'Недостаточно прав',
        insufficientRoleBody: 'Требуется роль **{role}** и выше, у вас — **{yourRole}**.',
        invalidPublicIdTitle: 'Неверный public_id',
        invalidPublicIdBody: 'public_id должен быть строкой из 43 символов.',
        invalidTimeTitle: 'Неверный формат времени',
        invalidTimeBody: 'Пример: `{example}`.',

        setRole: {
            selfTitle: 'Недопустимое действие',
            selfBody: 'Нельзя менять роль себе.',
            notFoundTitle: 'Аккаунт не найден',
            notFoundBody: 'Аккаунт с таким public_id не найден.',
            successTitle: 'Роль обновлена',
            successBody: '{identity}\nтеперь **{role}**{until}.',
            untilTimed: ' до <t:{timestamp}:f>',
            untilPermanent: ' (бессрочно)'
        },
        getRoleList: {
            empty: 'Пусто.',
            title: '📋 {role} — {count}',
            entry: '**{index}.** {identity}'
        },
        password: {
            roomUnavailableTitle: 'Комната недоступна',
            roomUnavailableBody: 'Комната **{room}** сейчас не запущена.',
            successTitle: 'Пароль обновлён',
            successSet: 'Комната **{room}**\nновый пароль: `{value}`',
            successCleared: 'Комната **{room}**\nпароль сброшен.'
        },
        statsClear: {
            successTitle: 'Статистика сброшена',
            successBody: 'Бекап: `{filename}`\nзаписей: {count}'
        },
        statsBackup: {
            successTitle: 'Бекап статистики создан',
            successBody: 'Файл: `{filename}`\nзаписей: {count}'
        },
        ban: {
            selfOrProtectedTitle: 'Недопустимое действие',
            selfOrProtectedBody: 'Нельзя забанить себя или игрока с защитой от бана.',
            successTitle: 'Игрок забанен',
            successBody: '{identity}\nна **{time}**{reason}\n{liveStatus}',
            liveKicked: '🔴 Был в комнате — кикнут немедленно.',
            liveOffline: 'Не в комнате — бан вступит в силу при следующем заходе.'
        },
        unban: {
            notFoundTitle: 'Не найдено',
            notFoundBody: 'Этот public_id не найден в бан-листе.',
            successTitle: 'Игрок разбанен'
        },
        mute: {
            protectedTitle: 'Недопустимое действие',
            protectedBody: 'У игрока защита от мута.',
            successTitle: 'Игрок замучен',
            successBody: '{identity}\nна **{time}**{reason}\n{liveStatus}',
            liveApplied: '🔴 Был в комнате — вступило в силу немедленно.',
            liveOffline: 'Не в комнате — мут применится при следующем заходе.'
        },
        unmute: {
            notFoundTitle: 'Не найдено',
            notFoundBody: 'Этот игрок не в муте.',
            successTitle: 'Игрок размучен',
            liveApplied: '\nПрименено немедленно.'
        },
        bans: {
            title: '📋 Бан-лист — {count}',
            empty: 'Пусто.',
            entry: '**{index}.** {identity}\nосталось: {mins}м'
        },
        mutes: {
            title: '📋 Мут-лист — {count}',
            empty: 'Пусто.',
            entry: '**{index}.** {identity}\nосталось: {mins}м'
        },
        tops: {
            notEnoughDataTitle: 'Недостаточно данных',
            notEnoughDataBody: 'Недостаточно игроков в топе: ещё {missing}.',
            allTitle: '📊 Топы игроков',
            statTitle: '📊 Топ: {stat}',
            sectionHeader: '**🏆 Топ по {stat}**\n{lines}',
            line: '`{index}.` **{name}** — {value}'
        },
        stats: {
            notFoundTitle: 'Не найдено',
            multipleFoundTitle: 'Найдено {count} игроков с ником "{nickname}"',
            multipleFoundBody: '{choices}\n\nПовторите команду с аргументом `index`, чтобы выбрать нужного.',
            choiceEntry: '[{index}] {name} ({auth}) - {games} игр',
            emptyTitle: 'Статистика не найдена',
            emptyBody: 'Нужно сыграть хотя бы одну игру.'
        },
        account: {
            adminOnlyTitle: 'Недостаточно прав',
            adminOnlyBody: 'Смотреть чужие аккаунты могут только ADMIN и выше.',
            notFoundTitle: 'Аккаунт не найден',
            title: '📋 {nickname}',
            body: '{identity}\n**роль:** {role}\n**до:** {until}\n**discord:** {discord}',
            untilPermanent: 'бессрочно',
            discordUnlinked: 'не привязан'
        },
        genericErrorTitle: 'Ошибка',
        genericErrorBody: 'Произошла ошибка при выполнении команды.',

        statsFields: {
            games: '**Игры:** {value}',
            wins: '**Победы:** {value} ({rate}%)',
            goals: '**Голы:** {value}',
            pob: '**ПОБ:** {value}% (из {total})',
            blocks: '**Блоки:** {value}',
            assists: '**Пасы:** {value}',
            errors: '**Ошибки:** {value} ({perGame}/игра)',
            serves: '**Подачи:** {value}',
            aces: '**ЭЙСы:** {value} ({rate}%)',
            time: '**Время:** {hours}ч'
        }
    }
};