name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /home/runner/volleyball
          git fetch origin main
          git reset --hard origin/main
          npm ci
          pm2 restart volleyball || pm2 start main.js --name "volleyball"
